# Generated by Django 4.0.5 on 2022-06-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название новой подкатегории', max_length=200, verbose_name='Название подкатегории')),
                ('image', models.ImageField(blank=True, upload_to='sub_category/', verbose_name='Картинка подкатегории')),
                ('description', models.TextField(help_text='Описание категории', verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название новой подкатегории', max_length=200, verbose_name='Название подкатегории')),
                ('image', models.ImageField(blank=True, upload_to='sub_category/', verbose_name='Картинка подкатегории')),
                ('description', models.TextField(help_text='Описание подкатегории', verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, help_text='Категория к которой относится пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='telebot.category', verbose_name='Подкатегория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название нового товара', max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Описание', verbose_name='Текст Описание')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Картинка продукта')),
                ('price', models.IntegerField(help_text='Цена продукта', verbose_name='Цена')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('sub_category', models.ForeignKey(blank=True, help_text='Подкатегория к которой относится пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='telebot.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
